### ISSUE TITLE
Docker image with version tag

### ISSUE THREAD

**Issue by gallardoalba** [josuebarrera/GenEra#15]
**Is your feature request related to a problem? Please describe.**
I would like to implement this tool in Galaxy, and in order to be able to specify the tool version when using the docker images it would be necessary to create a image with the tag corresponding to the tool version.

**Describe the solution you'd like**
It would be great if you could include a docker image with the tag corresponding to the tool version.

**Comment by josuebarrera** [comment]
Dear @gallardoalba,

I just uploaded the latest GenEra container with the tag "v1.2.0". You can find it [on the Docker hub page](https://hub.docker.com/r/josuebarrera/genera/tags). 

Saludos,
Josué.

**Comment by gallardoalba** [comment]
> Dear @gallardoalba,
> 
> I just uploaded the latest GenEra container with the tag "v1.2.0". You can find it [on the Docker hub page](https://hub.docker.com/r/josuebarrera/genera/tags).
> 
> Saludos, Josué.

Thanks a a lot!
